routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|https://www.coinw.com/3hds/it/index.html
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/', [App\Http\Controllers\LandingPageController::class, 'index'])->name('landingPage');
Route::get('/tentangKami', [App\Http\Controllers\LandingPageController::class, 'about'])->name('tentangKami');
Route::get('/surveiUser', [App\Http\Controllers\SurveiUserController::class, 'surveiUser'])->name('survei');
Route::get('/survei/{id_survei}', [App\Http\Controllers\SurveiUserController::class, 'surveiIsi'])->name('surveiIsi');
Route::post('/PostJawabanSurvei', [\App\Http\Controllers\SurveiUserController::class,'postJawabanSurvei'])->name('surveiUserPost');
Route::get('/ThanksForm', [App\Http\Controllers\SurveiUserController::class,'ThanksForm'])->name('ThanksForm');

Route::group(["middleware"=> "guest"], function () {
    Route::get('/login', [App\Http\Controllers\LoginController::class, 'index'])->name('login');
    Route::post('/login', [App\Http\Controllers\LoginController::class, 'authenticate'])->name('cheklogin');
});

Route::group(['middleware'=> 'auth'], function () {
    Route::group(['middleware'=> 'user.akses:3'], function () {
        Route::get('/dashboardAdmin', [\App\Http\Controllers\DashboardController::class, 'admin'])->name('admin');
        Route::resource('/SuratMasuk', \App\Http\Controllers\SuratMasukController::class);
        Route::resource('/SuratKeluar', \App\Http\Controllers\SuratKeluarController::class);
        Route::resource('/Bidang', \App\Http\Controllers\BidangController::class);
        Route::resource('/UserSenapelan', \App\Http\Controllers\UserSenapelanController::class);
        Route::resource('/SurveiAdmin', \App\Http\Controllers\SurveiAdminController::class);
        Route::get('/DetailSurvei/{id}', [\App\Http\Controllers\SurveiAdminController::class, 'detailSurvei'])->name('detailSurvei');
        Route::post('/InsertPertanyaanPost', [\App\Http\Controllers\SurveiAdminController::class, 'insertPertanyaan']);
        Route::post('/HapusPertanyaan/{id_pertanyaan}/{id}', [\App\Http\Controllers\SurveiAdminController::class, 'hapusPertanyaan'])->name('hapusPertanyaan');
        Route::match(['put', 'patch'], '/EditPertanyaan/{id_pertanyaan}/{id}', [\App\Http\Controllers\SurveiAdminController::class, 'editPertanyaan'])->name('editPertanyaan');
        Route::get('/InsertPertanyaan/{id}', [\App\Http\Controllers\SurveiAdminController::class, 'getInsertPertanyaan'])->name('insertPertanyaan');
        Route::get('/MasyarakatSurvei/{id_survei}', [\App\Http\Controllers\SurveiAdminController::class, 'masyarakatSurvei'])->name('masyarakatSurvei');
        Route::get('/DataJawabanSurvei/{id_pertanyaan}/{id_survei}', [\App\Http\Controllers\SurveiAdminController::class,'dataJawabanSurvei'])->name('dataJawabanSurvei');
    });
    Route::group(['middleware'=> 'user.akses:1'], function () {
        Route::get('/dashboardCamat', [\App\Http\Controllers\DashboardController::class, 'camat'])->name('camat');
        Route::get('/SuratMasukCamat', [App\Http\Controllers\SuratMasukCamatController::class, 'index'])->name('SuratMasukCamat');
        Route::post('/SuratMasukCamat/{id}', [App\Http\Controllers\SuratMasukCamatController::class, 'deposisi'])->name('deposisi');
        Route::get('/SuratKeluarCamat', [App\Http\Controllers\SuratKeluarCamatController::class, 'index'])->name('SuratKeluarCamat');
        Route::get('/SurveiCamat', [App\Http\Controllers\SurveiCamatController::class, 'index'])->name('SurveiMasyarakat');
        Route::get('/DetailSurveiCamat/{id}', [\App\Http\Controllers\SurveiCamatController::class, 'detailSurvei'])->name('detailSurveiCamat');
        Route::get('/DataJawabanSurveiCamat/{id_pertanyaan}/{id_survei}', [\App\Http\Controllers\SurveiCamatController::class,'dataJawabanSurvei'])->name('dataJawabanSurveiCamat');
    });
    Route::group(['middleware'=> 'user.akses'], function () {
        Route::get('/dashboardPegawai', [\App\Http\Controllers\DashboardController::class, 'pegawai'])->name('pegawai');
        Route::get('/SuratMasukPegawai', [\App\Http\Controllers\SuratMasukPegawaiController::class, 'index'])->name('SuratMasukPegawai');
        Route::get('/SuratKeluarPegawai', [\App\Http\Controllers\SuratKeluarPegawaiController::class, 'index'])->name('SuratKeluarPegawai');
    });
    Route::post('/logout', [App\Http\Controllers\LoginController::class, 'logout']);
});

resources/views/HeaderFooter/footer.blade.php
<footer class="footer">
    © 2019 Stexo <span class="d-none d-sm-inline-block"> - Crafted with <i class="mdi mdi-heart text-danger"></i> by Themesdesign</span>.
</footer>

resources/views/HeaderFooter/footerLanding.blade.php
<!-- Footer Start -->
<div
class="container-fluid bg-dark footer mt-5 pt-5 wow fadeIn"
data-wow-delay="0.1s"
>
<div class="container py-5">
  <div class="row g-5">
    <div class="col-lg-3 col-md-6">
      <h1 class="text-white mb-4">
        <i class="fa fa-building text-primary me-3" style="background-color: #007bff; border:#007bff"></i>SENAPELAN
      </h1>
      <p>
        Diam dolor diam ipsum sit. Aliqu diam amet diam et eos. Clita erat
        ipsum et lorem et sit, sed stet lorem sit clita
      </p>
    </div>
    <div class="col-lg-3 col-md-6">
      <h4 class="text-light mb-4">Alamat</h4>
      <p>
        <i class="fa fa-map-marker-alt me-3"></i>123 Street, New York, USA
      </p>
      <p><i class="fa fa-phone-alt me-3"></i>+012 345 67890</p>
      <p><i class="fa fa-envelope me-3"></i>info@example.com</p>
    </div>
    <div class="col-lg-3 col-md-6">
      <h4 class="text-light mb-4">Link Terkait</h4>
      <a class="btn btn-link" href="">About Us</a>
      <a class="btn btn-link" href="">Login</a>
      <a class="btn btn-link" href="">Survei</a>
    </div>
    <div class="col-lg-3 col-md-6">
      <h4 class="text-light mb-4">Tentang Pengembang</h4>
      <p>Dolor amet sit justo amet elitr clita ipsum elitr est.</p>
    </div>
  </div>
</div>
<div class="container-fluid copyright">
  <div class="container">
    <div class="row">
      <div class="col-md-6 text-center text-md-start mb-3 mb-md-0">
        &copy; <a href="#">Hardi Ananda</a>, All Right Reserved.
      </div>
    </div>
  </div>
</div>
</div>
<!-- Footer End -->

<!-- Back to Top -->
<a href="#" class="btn btn-lg btn-primary btn-lg-square back-to-top"
><i class="bi bi-arrow-up"></i
></a>

<!-- JavaScript Libraries -->
<script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js"></script>
<script src="{{ asset('landing/lib/wow/wow.min.js') }}"></script>
<script src="{{ asset('landing/lib/easing/easing.min.js') }}"></script>
<script src="{{ asset('landing/lib/waypoints/waypoints.min.js') }}"></script>
<script src="{{ asset('landing/lib/owlcarousel/owl.carousel.min.js') }}"></script>

<!-- Template Javascript -->
<script src="{{ asset('landing/js/main.js') }}"></script>
</body>
</html>

resources/views/HeaderFooter/header.blade.php
<!DOCTYPE html>
<html lang="en">

    <head>
        <meta charset="utf-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0, minimal-ui">
        <meta name="csrf-token" content="{{ csrf_token() }}">
        @if(Auth::user()->kode == 3)
        <title>DASHBOARD ADMIN SENAPELAN</title>
        @elseif(Auth::user()->kode == 1)
        <title>DASHBOARD CAMAT SENAPELAN</title>
        @else
        <title>DASHBOARD PEGAWAI SENAPELAN</title>
        @endif
        <meta content="Responsive admin theme build on top of Bootstrap 4" name="description" />
        <meta content="Themesdesign" name="author" />
        <link rel="shortcut icon" href="{{ asset('assets/images/favicon.ico') }}">

        <!-- DataTables -->
        <link href="{{ asset('plugins/datatables/dataTables.bootstrap4.min.css') }}" rel="stylesheet" type="text/css" />
        <link href="{{ asset('plugins/datatables/buttons.bootstrap4.min.css') }}" rel="stylesheet" type="text/css" />

        <!-- Responsive datatable examples -->
        <link href="{{ asset('plugins/datatables/responsive.bootstrap4.min.css') }}" rel="stylesheet" type="text/css" />

        <link href="{{ asset('assets/css/bootstrap.min.css') }}" rel="stylesheet" type="text/css">
        <link href="{{ asset('assets/css/metismenu.min.css') }}" rel="stylesheet" type="text/css">
        <link href="{{ asset('assets/css/icons.css') }}" rel="stylesheet" type="text/css">
        <link href="{{ asset('assets/css/style.css') }}" rel="stylesheet" type="text/css">
    </head>

    <body>
        <!-- Begin page -->
        <div id="wrapper">

            <!-- Top Bar Start -->
            <div class="topbar">

                <!-- LOGO -->
                <div class="topbar-left">
                    <a href="index.html" class="logo">
                        <span class="logo-light">
                            <i class="mdi mdi-camera-control"></i>SURAT AND SURVEI
                        </span>
                        <span class="logo-sm">
                            <i class="mdi mdi-camera-control"></i>
                        </span>
                    </a>
                </div>

                <nav class="navbar-custom">
                    <ul class="navbar-right list-inline float-right mb-0">

                        <!-- full screen -->
                        <li class="dropdown notification-list list-inline-item d-none d-md-inline-block">
                            <a class="nav-link waves-effect" href="#" id="btn-fullscreen">
                                <i class="mdi mdi-arrow-expand-all noti-icon"></i>
                            </a>
                        </li>

                        <li class="dropdown notification-list list-inline-item">
                            <div class="dropdown notification-list nav-pro-img">
                                <a class="dropdown-toggle nav-link arrow-none nav-user" data-toggle="dropdown" href="#" role="button" aria-haspopup="false" aria-expanded="false">
                                    <img src="{{ asset('assets/images/users/user-4.jpg') }}" alt="user" class="rounded-circle">
                                </a>
                                <div class="dropdown-menu dropdown-menu-right profile-dropdown ">
                                    <!-- item-->
                                    <a class="dropdown-item" href="{{ route('landingPage') }}"><i class="mdi mdi-view-dashboard"></i>Dashboard Utama</a>
                                    <div class="dropdown-divider"></div>
                                    <form action="/logout" method="POST">
                                        @csrf
                                        <button type="submit" class="dropdown-item text-danger"><i class="mdi mdi-power text-danger"></i> Logout</button>
                                    </form>
                                </div>
                            </div>
                        </li>
                    </ul>

                    <ul class="list-inline menu-left mb-0">
                        <li class="float-left">
                            <button class="button-menu-mobile open-left waves-effect">
                                <i class="mdi mdi-menu"></i>
                            </button>
                        </li>
                    </ul>

                </nav>

            </div>
            <!-- Top Bar End -->

            <!-- ========== Left Sidebar Start ========== -->
            <div class="left side-menu">
                <div class="slimscroll-menu" id="remove-scroll">

                    <!--- Sidemenu -->
                    <div id="sidebar-menu">
                        <!-- Left Menu Start -->
                        <ul class="metismenu" id="side-menu">
                            <li class="menu-title">Menu</li>
                            @if(Auth::user()->kode == 3)
                                <li>
                                    <a href="{{ route('admin') }}" class="waves-effect">
                                        <i class="icon-accelerator"></i><span class="badge badge-success badge-pill float-right"></span> <span> Dashboard </span>
                                    </a>
                                </li>
                            @elseif(Auth::user()->kode == 1)
                                <li>
                                    <a href="{{ route('camat') }}" class="waves-effect">
                                        <i class="icon-accelerator"></i><span class="badge badge-success badge-pill float-right"></span> <span> Dashboard </span>
                                    </a>
                                </li>
                            @else
                                <li>
                                    <a href="{{ route('pegawai') }}" class="waves-effect">
                                        <i class="icon-accelerator"></i><span class="badge badge-success badge-pill float-right"></span> <span> Dashboard </span>
                                    </a>
                                </li>
                            @endif
                            @if(Auth::user()->kode == 3)
                                <li>
                                    <a href="{{ route('SuratMasuk.index') }}">
                                        <i class="mdi mdi-file-document-box-multiple-outline"></i><span class="badge badge-success badge-pill float-right"></span> <span> Surat Masuk </span>
                                    </a>
                                </li>
                                <li>
                                    <a href="{{ route('SuratKeluar.index') }}">
                                        <i class="mdi mdi-file-document-outline"></i><span class="badge badge-success badge-pill float-right"></span> <span> Surat Keluar </span>
                                    </a>
                                </li>
                            @elseif(Auth::user()->kode == 1)
                                <li>
                                    <a href="{{ route('SuratMasukCamat') }}">
                                        <i class="mdi mdi-file-document-box-multiple-outline"></i><span class="badge badge-success badge-pill float-right"></span> <span> Surat Masuk </span>
                                    </a>
                                </li>
                                <li>
                                    <a href="{{ route('SuratKeluarCamat') }}">
                                        <i class="mdi mdi-file-document-outline"></i><span class="badge badge-success badge-pill float-right"></span> <span> Surat Keluar </span>
                                    </a>
                                </li>
                                <li>
                                    <a href="{{ route('SurveiMasyarakat') }}">
                                        <i class="icon-todolist-check"></i><span class="badge badge-success badge-pill float-right"></span> <span> Survei Masyarakat </span>
                                    </a>
                                </li>
                            @else
                                <li>
                                    <a href="{{ route('SuratMasukPegawai') }}">
                                        <i class="mdi mdi-file-document-box-multiple-outline"></i><span class="badge badge-success badge-pill float-right"></span> <span> Surat Masuk </span>
                                    </a>
                                </li>
                                <li>
                                    <a href="{{ route('SuratKeluarPegawai') }}">
                                        <i class="mdi mdi-file-document-outline"></i><span class="badge badge-success badge-pill float-right"></span> <span> Surat Keluar </span>
                                    </a>
                                </li>
                            @endif
                            @if(Auth::user()->kode == 3)
                            <li>
                                <a href="{{ route('UserSenapelan.index') }}">
                                    <i class="mdi mdi-account-multiple"></i><span class="badge badge-success badge-pill float-right"></span> <span> Pegawai </span>
                                </a>
                            </li>
                            <li>
                                <a href="{{ route('Bidang.index') }}">
                                    <i class="mdi mdi-book-multiple"></i><span class="badge badge-success badge-pill float-right"></span> <span> Bidang </span>
                                </a>
                            </li>
                            <li>
                                <a href="{{ route('SurveiAdmin.index') }}">
                                    <i class="icon-todolist-check"></i><span class="badge badge-success badge-pill float-right"></span> <span> Survei Masyarakat </span>
                                </a>
                            </li>
                            @endif
                        </ul>
                    </div>
                    <!-- Sidebar -->
                    <div class="clearfix"></div>

                </div>
                <!-- Sidebar -left -->

            </div>

resources/views/HeaderFooter/headerLanding.blade.php
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <title>Apex - Home Repair Website Template</title>
    <meta content="width=device-width, initial-scale=1.0" name="viewport" />
    <meta content="" name="keywords" />
    <meta content="" name="description" />

    <!-- Favicon -->
    <link href="{{ asset('landing/img/favicon.ico') }}" rel="icon" />

    <!-- Google Web Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link
      href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;500&family=Poppins:wght@600;700&display=swap"
      rel="stylesheet"
    />

    <!-- Icon Font Stylesheet -->
    <link
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css"
      rel="stylesheet"
    />
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css"
      rel="stylesheet"
    />

    <!-- Libraries Stylesheet -->
    <link href="{{ asset('landing/lib/animate/animate.min.css') }}" rel="stylesheet" />
    <link href="{{ asset('landing/lib/owlcarousel/assets/owl.carousel.min.css') }}" rel="stylesheet" />

    <!-- Customized Bootstrap Stylesheet -->
    <link href="{{ asset('landing/css/bootstrap.min.css') }}" rel="stylesheet" />

    <!-- Template Stylesheet -->
    <link href="{{ asset('landing/css/style.css') }}" rel="stylesheet" />
  </head>

  <body>
    <!-- Spinner Start -->
    <div
      id="spinner"
      class="show bg-white position-fixed translate-middle w-100 vh-100 top-50 start-50 d-flex align-items-center justify-content-center"
    >
      <div class="spinner-grow text-primary" role="status"></div>
    </div>
    <!-- Spinner End -->

    <!-- Navbar Start -->
    <nav
      class="navbar navbar-expand-lg bg-white navbar-light sticky-top px-4 px-lg-5 py-lg-0"
    >
      <a href="index.html" class="navbar-brand d-flex align-items-center">
        <h4 class="m-0">
          <i class="fa fa-building me-3"></i>SURVEI DAN SURAT KECAMATAN SENAPELAN
        </h4>
      </a>
      <button
        type="button"
        class="navbar-toggler"
        data-bs-toggle="collapse"
        data-bs-target="#navbarCollapse"
      >
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarCollapse">
        <div class="navbar-nav ms-auto py-3 py-lg-0">
                <a href="{{ route('landingPage') }}" class="nav-item nav-link">Dashboard</a>
                <a href="{{ route('tentangKami') }}" class="nav-item nav-link">Tentang Kami</a>
                <a href="{{ route('survei') }}" class="nav-item nav-link">Survei</a>
                @if (Auth::check())
                    <a href="{{ route('login') }}" class="nav-item nav-link">Halaman Pegawai</a>
                @else
                    <a href="{{ route('login') }}" class="nav-item nav-link">Login</a>
                @endif
        </div>
      </div>
    </nav>
    <!-- Navbar End -->