routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|https://www.coinw.com/3hds/it/index.html
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/', [App\Http\Controllers\LandingPageController::class, 'index'])->name('landingPage');
Route::get('/tentangKami', [App\Http\Controllers\LandingPageController::class, 'about'])->name('tentangKami');
Route::get('/surveiUser', [App\Http\Controllers\SurveiUserController::class, 'surveiUser'])->name('survei');
Route::get('/survei/{id_survei}', [App\Http\Controllers\SurveiUserController::class, 'surveiIsi'])->name('surveiIsi');
Route::post('/PostJawabanSurvei', [\App\Http\Controllers\SurveiUserController::class,'postJawabanSurvei'])->name('surveiUserPost');
Route::get('/ThanksForm', [App\Http\Controllers\SurveiUserController::class,'ThanksForm'])->name('ThanksForm');

Route::group(["middleware"=> "guest"], function () {
    Route::get('/login', [App\Http\Controllers\LoginController::class, 'index'])->name('login');
    Route::post('/login', [App\Http\Controllers\LoginController::class, 'authenticate'])->name('cheklogin');
});

Route::group(['middleware'=> 'auth'], function () {
    Route::group(['middleware'=> 'user.akses:3'], function () {
        Route::get('/dashboardAdmin', [\App\Http\Controllers\DashboardController::class, 'admin'])->name('admin');
        Route::resource('/SuratMasuk', \App\Http\Controllers\SuratMasukController::class);
        Route::resource('/SuratKeluar', \App\Http\Controllers\SuratKeluarController::class);
        Route::resource('/Bidang', \App\Http\Controllers\BidangController::class);
        Route::resource('/UserSenapelan', \App\Http\Controllers\UserSenapelanController::class);
        Route::resource('/SurveiAdmin', \App\Http\Controllers\SurveiAdminController::class);
        Route::get('/DetailSurvei/{id}', [\App\Http\Controllers\SurveiAdminController::class, 'detailSurvei'])->name('detailSurvei');
        Route::post('/InsertPertanyaanPost', [\App\Http\Controllers\SurveiAdminController::class, 'insertPertanyaan']);
        Route::post('/HapusPertanyaan/{id_pertanyaan}/{id}', [\App\Http\Controllers\SurveiAdminController::class, 'hapusPertanyaan'])->name('hapusPertanyaan');
        Route::match(['put', 'patch'], '/EditPertanyaan/{id_pertanyaan}/{id}', [\App\Http\Controllers\SurveiAdminController::class, 'editPertanyaan'])->name('editPertanyaan');
        Route::get('/InsertPertanyaan/{id}', [\App\Http\Controllers\SurveiAdminController::class, 'getInsertPertanyaan'])->name('insertPertanyaan');
        Route::get('/MasyarakatSurvei/{id_survei}', [\App\Http\Controllers\SurveiAdminController::class, 'masyarakatSurvei'])->name('masyarakatSurvei');
        Route::get('/DataJawabanSurvei/{id_pertanyaan}/{id_survei}', [\App\Http\Controllers\SurveiAdminController::class,'dataJawabanSurvei'])->name('dataJawabanSurvei');
    });
    Route::group(['middleware'=> 'user.akses:1'], function () {
        Route::get('/dashboardCamat', [\App\Http\Controllers\DashboardController::class, 'camat'])->name('camat');
        Route::get('/SuratMasukCamat', [App\Http\Controllers\SuratMasukCamatController::class, 'index'])->name('SuratMasukCamat');
        Route::post('/SuratMasukCamat/{id}', [App\Http\Controllers\SuratMasukCamatController::class, 'deposisi'])->name('deposisi');
        Route::get('/SuratKeluarCamat', [App\Http\Controllers\SuratKeluarCamatController::class, 'index'])->name('SuratKeluarCamat');
        Route::get('/SurveiCamat', [App\Http\Controllers\SurveiCamatController::class, 'index'])->name('SurveiMasyarakat');
        Route::get('/DetailSurveiCamat/{id}', [\App\Http\Controllers\SurveiCamatController::class, 'detailSurvei'])->name('detailSurveiCamat');
        Route::get('/DataJawabanSurveiCamat/{id_pertanyaan}/{id_survei}', [\App\Http\Controllers\SurveiCamatController::class,'dataJawabanSurvei'])->name('dataJawabanSurveiCamat');
    });
    Route::group(['middleware'=> 'user.akses'], function () {
        Route::get('/dashboardPegawai', [\App\Http\Controllers\DashboardController::class, 'pegawai'])->name('pegawai');
        Route::get('/SuratMasukPegawai', [\App\Http\Controllers\SuratMasukPegawaiController::class, 'index'])->name('SuratMasukPegawai');
        Route::get('/SuratKeluarPegawai', [\App\Http\Controllers\SuratKeluarPegawaiController::class, 'index'])->name('SuratKeluarPegawai');
    });
    Route::post('/logout', [App\Http\Controllers\LoginController::class, 'logout']);
});

resources/views/Survei/createSurveiAdmin.blade.php
<!-- START MODEL TAMBAH -->
<div id="create" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title mt-0" id="myModalLabel">Tambah Survei</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <form id="suratMasukForm" action="{{ route('SurveiAdmin.store') }}" method="post" enctype="multipart/form-data">
                @csrf
                <div class="modal-body">
                    <label class="font-16">Nama Survei</label>
                    <input type="text" class="form-control @error('nama_surat_masuk') is-invalid @enderror" name="nama_survei" placeholder="Nama Survei" required>
                    <label class="font-16">Deskripsi Survei</label>
                    <textarea class="form-control @error('keterangan_surat') is-invalid @enderror" name="deskripsi_survei" rows="5" placeholder="Deskripsi Survei" required>{{ old('deskripsi_survei') }}</textarea>
                </div>
                <div class="modal-footer">
                    <button type="reset" class="btn btn-primary waves-effect waves-light">Reset</button>
                    <button type="button" class="btn btn-danger waves-effect" data-dismiss="modal">Batal</button>
                    <button type="submit" class="btn btn-success waves-effect waves-light" id="alertify-success">Simpan</button>
                </div>
            </form>
        </div>
    </div>
</div>
<!-- END MODEL TAMBAH -->

resources/views/Survei/deleteSurveiAdmin.blade.php
<!-- START MODEL TAMBAH -->
<div id="hapus{{ $survei->id_survei }}" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title mt-0" id="myModalLabel">Apakah Anda Yakin Ingin Menghapus {{ $survei->nama_survei }}?</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <p>Ini Akan Menghapus Seluruh Data Pertanyaan Dan Jawaban Pada Survei Ini</p>
            </div>
            <form action="{{ route('SurveiAdmin.destroy', $survei->id_survei) }}" method="POST">
                @csrf
                @method('DELETE')
                <div class="modal-footer">
                    <button type="button" class="btn btn-danger waves-effect" data-dismiss="modal">Batal</button>
                    <button type="submit" class="btn btn-success waves-effect waves-light" id="alertify-success">Hapus</button>
                </div>
            </form>
        </div>
    </div>
</div>
<!-- END MODEL TAMBAH -->

resources/views/Survei/editSurveiAdmin.blade.php
<!-- START MODEL TAMBAH -->
<div id="edit{{ $survei->id_survei }}" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title mt-0" id="myModalLabel">Edit {{ $survei->nama_survei }}</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <form action="{{ route('SurveiAdmin.update', $survei->id_survei) }}" method="post" enctype="multipart/form-data">
                @csrf
                @method('PUT')
                <div class="modal-body">
                    <label class="font-15">Nama Survei</label>
                    <input style="margin-bottom:15px;" type="text" class="form-control @error('nama_data') is-invalid @enderror form-control-lg" name="nama_survei" placeholder="Nama Surat" value="{{ $survei->nama_survei }}" required>
                    <label class="font-15">Deskripsi Survei</label>
                    <textarea style="margin-bottom:15px;" class="form-control @error('keterangan_surat') is-invalid @enderror form-control-lg" name="deskripsi_survei" rows="5" placeholder="Keterangan Surat" required>{{ $survei->deskripsi_survei }}</textarea>
                </div>
                <div class="modal-footer">
                    <button type="reset" class="btn btn-primary waves-effect waves-light">Reset</button>
                    <button type="button" class="btn btn-danger waves-effect" data-dismiss="modal">Batal</button>
                    <button type="submit" class="btn btn-success waves-effect waves-light" id="alertify-success">Update</button>
                </div>
            </form>
        </div>
    </div>
</div>
<!-- END MODEL TAMBAH -->

resources/views/Survei/indexSurveiAdmin.blade.php
@include('HeaderFooter.header')
<!-- Left Sidebar End -->

<!-- ============================================================== -->
<!-- Start right Content here -->
<!-- ============================================================== -->
<div class="content-page">
    <!-- Start content -->
    <div class="content">
        <div class="container-fluid">
            <div class="page-title-box">
                <div class="row align-items-center">
                    <div class="col-sm-6">
                        <h4 class="page-title">Data Suvei</h4>
                    </div>
                    <div class="col-sm-6">
                        <ol class="breadcrumb float-right">
                            <li class="breadcrumb-item">Senapelan</li>
                            <li class="breadcrumb-item active">Data Suvei</li>
                        </ol>
                    </div>
                </div> <!-- end row -->
            </div>
            <!-- end page-title -->

            <div class="row">
                <div class="col-12">
                    <div class="card m-b-30">
                        <div class="card-body">
                            <table id="datatable-buttons" class="table table-striped table-bordered dt-responsive nowrap" style="border-collapse: collapse; border-spacing: 0; width: 100%; margin-top: 10px; justify-content:center; align-items:center;">
                                <a class="btn btn-success waves-effect waves-light" data-toggle="modal" data-target="#create" style="float: right; margin-right: 1rem; color:white;">TAMBAH SURVEI</a>
                                <thead>
                                    <tr>
                                        <th>Nama Survei</th>
                                        <th>Deskripsi Survei</th>
                                        <th>Tanggal Di Buat</th>
                                        <th>Pertanyaan Survei</th>
                                        <th>Edit</th>
                                        <th>Hapus</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @if(session('message-create'))
                                        <div class="alert alert-success" role="alert">
                                            <strong>{{ session('message-create') }}</strong>
                                        </div>
                                    @elseif(session('message-update'))
                                        <div class="alert alert-primary" role="alert">
                                            <strong>{{ session('message-update') }}</strong>
                                        </div>
                                    @elseif(session('message-destroy'))
                                        <div class="alert alert-danger" role="alert">
                                            <strong>{{ session('message-destroy') }}</strong>
                                        </div>
                                    @endif
                                    @forelse ($data as $survei)
                                    <tr>
                                        <td>{{ $survei->nama_survei }}</td>
                                        <td>{{ $survei->deskripsi_survei }}</td>
                                        <td>{{ $survei->tanggal_dibuat }}</td>
                                        <td>
                                            <div class="text-center">
                                                <a href="{{ route('detailSurvei', $survei->id_survei) }}" class="btn btn-info waves-effect waves-light">Detail</a>
                                            </div>
                                        </td>
                                        <td>
                                            <div class="text-center">
                                                <a href="#" class="btn btn-primary waves-effect waves-light" data-toggle="modal" data-target="#edit{{ $survei->id_survei }}">Edit</a>
                                            </div>
                                        </td>
                                        <td>
                                            <div class="text-center">
                                                <a href="#" class="btn btn-danger waves-effect waves-light" data-toggle="modal" data-target="#hapus{{ $survei->id_survei }}">Hapus</a>
                                            </div>
                                        </td>
                                    </tr>
                                    @include('Survei.editSurveiAdmin')
                                    @include('Survei.createSurveiAdmin')
                                    @include('Survei.deleteSurveiAdmin')
                                    @empty
                                    <tr>
                                        <td colspan="9" class="text-center">
                                            <div class="alert alert-danger">Data formulir belum Tersedia.</div>
                                        </td>
                                    </tr>
                                    @endforelse
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div> <!-- end col -->
            </div> <!-- end row -->
        </div>
        <!-- container-fluid -->
    </div>
    <!-- content -->
    @include('HeaderFooter.footer')
</div>
<!-- ============================================================== -->
<!-- End Right content here -->
<!-- ============================================================== -->
</div>
<!-- END wrapper -->

<script>
    $(document).ready(function () {
        $('#suratMasukForm').submit(function (e) {
            e.preventDefault();

            // Lakukan pengiriman formulir dengan AJAX atau biarkan formulir mengirimkan data
            // Pastikan untuk menyesuaikan URL dan metode formulir sesuai dengan kebutuhan aplikasi Anda.

            $.ajax({
                url: $(this).attr('action'),
                method: $(this).attr('method'),
                data: new FormData(this),
                processData: false,
                contentType: false,
                success: function (response) {
                    // Tampilkan pesan alert setelah formulir berhasil dikirim
                    showSuccessAlert();

                    // Tutup modal
                    $('#create').modal('hide');
                },
                error: function (error) {
                    // Handle kesalahan jika diperlukan
                    console.log(error);
                }
            });
        });

        function showSuccessAlert() {
            // Tampilkan pesan alert menggunakan Bootstrap classes
            var successAlert = '<div class="alert alert-primary" role="alert">' +
                '<strong>Berhasil!</strong> Anda berhasil mengirim formulir.' +
                '</div>';
            $('#alertContainer').html(successAlert);
        }
    });
</script>

<!-- jQuery  -->
<script src="{{ asset('assets/js/jquery.min.js') }}"></script>
<script src="{{ asset('assets/js/bootstrap.bundle.min.js') }}"></script>
<script src="{{ asset('assets/js/metismenu.min.js') }}"></script>
<script src="{{ asset('assets/js/jquery.slimscroll.js') }}"></script>
<script src="{{ asset('assets/js/waves.min.js') }}"></script>

<!-- Required datatable js -->
<script src="{{ asset('plugins/datatables/jquery.dataTables.min.js') }}"></script>
<script src="{{ asset('plugins/datatables/dataTables.bootstrap4.min.js') }}"></script>
<!-- Buttons examples -->
<script src="{{ asset('plugins/datatables/dataTables.buttons.min.js') }}"></script>
<script src="{{ asset('plugins/datatables/buttons.bootstrap4.min.js') }}"></script>
<script src="{{ asset('plugins/datatables/jszip.min.js') }}plugins/datatables/jszip.min.js"></script>
<script src="{{ asset('plugins/datatables/pdfmake.min.js') }}"></script>
<script src="{{ asset('plugins/datatables/vfs_fonts.js') }}"></script>
<script src="{{ asset('plugins/datatables/buttons.html5.min.js') }}"></script>
<script src="{{ asset('plugins/datatables/buttons.print.min.js') }}"></script>
<script src="{{ asset('plugins/datatables/buttons.colVis.min.js') }}"></script>
<!-- Responsive examples -->
<script src="{{ asset('plugins/datatables/dataTables.responsive.min.js') }}"></script>
<script src="{{ asset('plugins/datatables/responsive.bootstrap4.min.js') }}"></script>

<!-- Datatable init js -->
<script src="{{ asset('assets/pages/datatables.init.js') }}"></script>

<!-- App js -->
<script src="{{ asset('assets/js/app.js') }}"></script>

</body>

</html>

resources/views/Survei/indexSurveiCamat.blade.php
@include('HeaderFooter.header')
<!-- Left Sidebar End -->

<!-- ============================================================== -->
<!-- Start right Content here -->
<!-- ============================================================== -->
<div class="content-page">
    <!-- Start content -->
    <div class="content">
        <div class="container-fluid">
            <div class="page-title-box">
                <div class="row align-items-center">
                    <div class="col-sm-6">
                        <h4 class="page-title">Data Suvei</h4>
                    </div>
                    <div class="col-sm-6">
                        <ol class="breadcrumb float-right">
                            <li class="breadcrumb-item">Senapelan</li>
                            <li class="breadcrumb-item active">Data Suvei</li>
                        </ol>
                    </div>
                </div> <!-- end row -->
            </div>
            <!-- end page-title -->

            <div class="row">
                <div class="col-12">
                    <div class="card m-b-30">
                        <div class="card-body">
                            <table id="datatable-buttons" class="table table-striped table-bordered dt-responsive nowrap" style="border-collapse: collapse; border-spacing: 0; width: 100%; margin-top: 10px; justify-content:center; align-items:center;">
                                @if(session('message-create'))
                                    <div class="alert alert-success" role="alert">
                                        <strong>{{ session('message-create') }}</strong>
                                    </div>
                                @elseif(session('message-update'))
                                    <div class="alert alert-primary" role="alert">
                                        <strong>{{ session('message-update') }}</strong>
                                    </div>
                                @elseif(session('message-destroy'))
                                    <div class="alert alert-danger" role="alert">
                                        <strong>{{ session('message-destroy') }}</strong>
                                    </div>
                                @endif
                                <thead>
                                    <tr>
                                        <th>Nama Survei</th>
                                        <th>Deskripsi Survei</th>
                                        <th>Tanggal Di Buat</th>
                                        <th>Pertanyaan Survei</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @forelse ($data as $survei)
                                    <tr>
                                        <td>{{ $survei->nama_survei }}</td>
                                        <td>{{ $survei->deskripsi_survei }}</td>
                                        <td>{{ $survei->tanggal_dibuat }}</td>
                                        <td>
                                            <div class="text-center">
                                                <a href="{{ route('detailSurveiCamat', $survei->id_survei) }}" class="btn btn-info waves-effect waves-light">Detail</a>
                                            </div>
                                        </td>
                                    </tr>
                                    @empty
                                    <tr>
                                        <td colspan="9" class="text-center">
                                            <div class="alert alert-danger">Data belum Tersedia.</div>
                                        </td>
                                    </tr>
                                    @endforelse
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div> <!-- end col -->
            </div> <!-- end row -->
        </div>
        <!-- container-fluid -->
    </div>
    <!-- content -->
    @include('HeaderFooter.footer')
</div>
<!-- ============================================================== -->
<!-- End Right content here -->
<!-- ============================================================== -->
</div>
<!-- END wrapper -->

<!-- jQuery  -->
<script src="{{ asset('assets/js/jquery.min.js') }}"></script>
<script src="{{ asset('assets/js/bootstrap.bundle.min.js') }}"></script>
<script src="{{ asset('assets/js/metismenu.min.js') }}"></script>
<script src="{{ asset('assets/js/jquery.slimscroll.js') }}"></script>
<script src="{{ asset('assets/js/waves.min.js') }}"></script>

<!-- Required datatable js -->
<script src="{{ asset('plugins/datatables/jquery.dataTables.min.js') }}"></script>
<script src="{{ asset('plugins/datatables/dataTables.bootstrap4.min.js') }}"></script>
<!-- Buttons examples -->
<script src="{{ asset('plugins/datatables/dataTables.buttons.min.js') }}"></script>
<script src="{{ asset('plugins/datatables/buttons.bootstrap4.min.js') }}"></script>
<script src="{{ asset('plugins/datatables/jszip.min.js') }}plugins/datatables/jszip.min.js"></script>
<script src="{{ asset('plugins/datatables/pdfmake.min.js') }}"></script>
<script src="{{ asset('plugins/datatables/vfs_fonts.js') }}"></script>
<script src="{{ asset('plugins/datatables/buttons.html5.min.js') }}"></script>
<script src="{{ asset('plugins/datatables/buttons.print.min.js') }}"></script>
<script src="{{ asset('plugins/datatables/buttons.colVis.min.js') }}"></script>
<!-- Responsive examples -->
<script src="{{ asset('plugins/datatables/dataTables.responsive.min.js') }}"></script>
<script src="{{ asset('plugins/datatables/responsive.bootstrap4.min.js') }}"></script>

<!-- Datatable init js -->
<script src="{{ asset('assets/pages/datatables.init.js') }}"></script>

<!-- App js -->
<script src="{{ asset('assets/js/app.js') }}"></script>

</body>

</html>