routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|https://www.coinw.com/3hds/it/index.html
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/', [App\Http\Controllers\LandingPageController::class, 'index'])->name('landingPage');
Route::get('/tentangKami', [App\Http\Controllers\LandingPageController::class, 'about'])->name('tentangKami');
Route::get('/surveiUser', [App\Http\Controllers\SurveiUserController::class, 'surveiUser'])->name('survei');
Route::get('/survei/{id_survei}', [App\Http\Controllers\SurveiUserController::class, 'surveiIsi'])->name('surveiIsi');
Route::post('/PostJawabanSurvei', [\App\Http\Controllers\SurveiUserController::class,'postJawabanSurvei'])->name('surveiUserPost');
Route::get('/ThanksForm', [App\Http\Controllers\SurveiUserController::class,'ThanksForm'])->name('ThanksForm');

Route::group(["middleware"=> "guest"], function () {
    Route::get('/login', [App\Http\Controllers\LoginController::class, 'index'])->name('login');
    Route::post('/login', [App\Http\Controllers\LoginController::class, 'authenticate'])->name('cheklogin');
});

Route::group(['middleware'=> 'auth'], function () {
    Route::group(['middleware'=> 'user.akses:3'], function () {
        Route::get('/dashboardAdmin', [\App\Http\Controllers\DashboardController::class, 'admin'])->name('admin');
        Route::resource('/SuratMasuk', \App\Http\Controllers\SuratMasukController::class);
        Route::resource('/SuratKeluar', \App\Http\Controllers\SuratKeluarController::class);
        Route::resource('/Bidang', \App\Http\Controllers\BidangController::class);
        Route::resource('/UserSenapelan', \App\Http\Controllers\UserSenapelanController::class);
        Route::resource('/SurveiAdmin', \App\Http\Controllers\SurveiAdminController::class);
        Route::get('/DetailSurvei/{id}', [\App\Http\Controllers\SurveiAdminController::class, 'detailSurvei'])->name('detailSurvei');
        Route::post('/InsertPertanyaanPost', [\App\Http\Controllers\SurveiAdminController::class, 'insertPertanyaan']);
        Route::post('/HapusPertanyaan/{id_pertanyaan}/{id}', [\App\Http\Controllers\SurveiAdminController::class, 'hapusPertanyaan'])->name('hapusPertanyaan');
        Route::match(['put', 'patch'], '/EditPertanyaan/{id_pertanyaan}/{id}', [\App\Http\Controllers\SurveiAdminController::class, 'editPertanyaan'])->name('editPertanyaan');
        Route::get('/InsertPertanyaan/{id}', [\App\Http\Controllers\SurveiAdminController::class, 'getInsertPertanyaan'])->name('insertPertanyaan');
        Route::get('/MasyarakatSurvei/{id_survei}', [\App\Http\Controllers\SurveiAdminController::class, 'masyarakatSurvei'])->name('masyarakatSurvei');
        Route::get('/DataJawabanSurvei/{id_pertanyaan}/{id_survei}', [\App\Http\Controllers\SurveiAdminController::class,'dataJawabanSurvei'])->name('dataJawabanSurvei');
    });
    Route::group(['middleware'=> 'user.akses:1'], function () {
        Route::get('/dashboardCamat', [\App\Http\Controllers\DashboardController::class, 'camat'])->name('camat');
        Route::get('/SuratMasukCamat', [App\Http\Controllers\SuratMasukCamatController::class, 'index'])->name('SuratMasukCamat');
        Route::post('/SuratMasukCamat/{id}', [App\Http\Controllers\SuratMasukCamatController::class, 'deposisi'])->name('deposisi');
        Route::get('/SuratKeluarCamat', [App\Http\Controllers\SuratKeluarCamatController::class, 'index'])->name('SuratKeluarCamat');
        Route::get('/SurveiCamat', [App\Http\Controllers\SurveiCamatController::class, 'index'])->name('SurveiMasyarakat');
        Route::get('/DetailSurveiCamat/{id}', [\App\Http\Controllers\SurveiCamatController::class, 'detailSurvei'])->name('detailSurveiCamat');
        Route::get('/DataJawabanSurveiCamat/{id_pertanyaan}/{id_survei}', [\App\Http\Controllers\SurveiCamatController::class,'dataJawabanSurvei'])->name('dataJawabanSurveiCamat');
    });
    Route::group(['middleware'=> 'user.akses'], function () {
        Route::get('/dashboardPegawai', [\App\Http\Controllers\DashboardController::class, 'pegawai'])->name('pegawai');
        Route::get('/SuratMasukPegawai', [\App\Http\Controllers\SuratMasukPegawaiController::class, 'index'])->name('SuratMasukPegawai');
        Route::get('/SuratKeluarPegawai', [\App\Http\Controllers\SuratKeluarPegawaiController::class, 'index'])->name('SuratKeluarPegawai');
    });
    Route::post('/logout', [App\Http\Controllers\LoginController::class, 'logout']);
});

app/Http/Controllers/UserSenapelanController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\UserSenapelanModel;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;
use Illuminate\Support\Facades\Auth;
class UserSenapelanController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data = UserSenapelanModel::with('bidang')->paginate(10);
        $data2 = DB::SELECT(DB::raw("SELECT * FROM bidang"));
        return view('UserSenapelan.indexAdmin', compact('data', 'data2'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('UserSenapelan.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'nama' => 'required',
            'email' => 'required',
            'password' => 'required',
            'bidang' => 'required',
        ]);
        $pass = bcrypt($request->password);
        $now = now();
        //Insert Data
        DB::insert("INSERT INTO users (
            `name`,
            `email`,
            `email_verified_at`,
            `password`,
            `remember_token`,
            `kode`,
            `created_at`,
            `updated_at`)
            VALUES (?, ?, ?, ?, ?, ?, ?, ?)",
            [
                $request->nama,
                $request->email,
                $now,
                $pass,
                Str::random(10),
                $request->bidang,
                $now,
                $now
            ]
        );

        return redirect()->route('UserSenapelan.index')->with('message-create', 'Pegawai Berhasil Di Tambahkan!');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        if(Auth::user()->id == $id){
            return redirect()->route('UserSenapelan.index')->with('message-danger', 'Bidang Gagal Di Perbarui!');
        }
        else{
            $this->validate($request, [
                'nama' => 'required',
                'bidang' => 'required',
            ]);

            DB::update("UPDATE users SET
                `name` = ?,
                `kode` = ?
                WHERE `id` = ?", [
                    $request->nama,
                    $request->bidang,
                    $id
                ]
            );
            return redirect()->route('UserSenapelan.index')->with('message-update', 'Pegawai Berhasil Di Perbarui!');
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        DB::table('users')->where('id', $id)->delete();
        return redirect()->route('UserSenapelan.index')->with('message-destroy', 'Pegawai Berhasil Di Hapus!');
    }
}

resources/views/UserSenapelan/createAdmin.blade.php
<!-- START MODEL TAMBAH -->
<div id="create" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title mt-0" id="myModalLabel">Tambah Pegawai</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <form action="{{ route('UserSenapelan.store') }}" method="post" enctype="multipart/form-data">
                @csrf
                <div class="modal-body">
                    <div class="modal-body">
                        <label class="font-16">Nama Pegawai</label>
                        <input type="text" class="form-control @error('lampiran') is-invalid @enderror" name="nama" placeholder="Nama Pegawai" required>
                        <label class="font-16">Email</label>
                        <input type="text" class="form-control @error('lampiran') is-invalid @enderror" name="email" placeholder="Email" required>
                        <label class="font-16">Password</label>
                        <input type="text" class="form-control @error('lampiran') is-invalid @enderror" name="password" placeholder="Password" required>
                        <label class="font-16" for="exampleDropdown">Jabatan</label>
                        <select class="form-control" name="bidang" required id="exampleDropdown">
                            @forelse ($data2 as $jabatan)
                            <option value="{{ $jabatan->kode }}">{{ $jabatan->bidang }}</option>
                            @empty
                            <option value="Data Kosong">Data Kosong</option>
                            @endforelse
                        </select>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="reset" class="btn btn-primary waves-effect waves-light">Reset</button>
                    <button type="button" class="btn btn-danger waves-effect" data-dismiss="modal">Batal</button>
                    <button type="submit" class="btn btn-success waves-effect waves-light" id="alertify-success">Simpan</button>
                </div>
            </form>
        </div>
    </div>
</div>
<div id="alertContainer"> </div>
<!-- END MODEL TAMBAH -->

resources/views/UserSenapelan/deleteAdmin.blade.php
<div id="hapus{{ $user->id }}" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title mt-0" id="myModalLabel">Apakah Anda Yakin Ingin Menghapus {{ $user->name }}?</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <form action="{{ route('UserSenapelan.destroy', $user->id) }}" method="POST">
                @csrf
                @method('DELETE')
                <div class="modal-footer">
                    <button type="button" class="btn btn-danger waves-effect" data-dismiss="modal">Batal</button>
                    <button type="submit" class="btn btn-success waves-effect waves-light" id="alertify-success">Hapus</button>
                </div>
            </form>
        </div>
    </div>
</div>

resources/views/UserSenapelan/editAdmin.blade.php
<!-- START MODEL EDIT -->
<div id="edit{{ $user->id }}" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title mt-0" id="myModalLabel">Edit Data {{ $user->name }}</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <form action="{{ route('UserSenapelan.update', $user->id) }}" method="post" enctype="multipart/form-data">
                @csrf
                @method('PUT')
                <div class="modal-body">
                    <label class="font-16">Nama Pegawai</label>
                    <input type="text" class="form-control @error('lampiran') is-invalid @enderror" name="nama" placeholder="Nama Surat" value="{{ $user->name }}" required>
                    <br>
                    <label class="font-16">Bidang Pegawai</label>
                    <select class="form-control" name="bidang" id="exampleDropdown">
                        <option value=""></option>
                        @forelse ($data2 as $jabatan)
                        <option value="{{ $jabatan->kode }}">{{ $jabatan->bidang }}</option>
                        @empty
                        <option value="Data Kosong">Data Kosong</option>
                        @endforelse
                    </select>
                </div>
                <div class="modal-footer">
                    <button type="reset" class="btn btn-primary waves-effect waves-light">Reset</button>
                    <button type="button" class="btn btn-danger waves-effect" data-dismiss="modal">Batal</button>
                    <button type="submit" class="btn btn-success waves-effect waves-light" id="alertify-success">Update</button>
                </div>
            </form>
        </div>
    </div>
</div>
<!-- END MODEL EDIT -->

resources/views/UserSenapelan/indexAdmin.blade.php
@include('HeaderFooter.header')
<!-- Left Sidebar End -->

<!-- ============================================================== -->
<!-- Start right Content here -->
<!-- ============================================================== -->
<div class="content-page">
    <!-- Start content -->
    <div class="content">
        <div class="container-fluid">
            <div class="page-title-box">
                <div class="row align-items-center">
                    <div class="col-sm-6">
                        <h4 class="page-title">Data Pegawai</h4>
                    </div>
                    <div class="col-sm-6">
                        <ol class="breadcrumb float-right">
                            <li class="breadcrumb-item">Senapelan</li>
                            <li class="breadcrumb-item active">Data Pegawai</li>
                        </ol>
                    </div>
                </div> <!-- end row -->
            </div>
            <!-- end page-title -->

            <div class="row">
                <div class="col-12">
                    <div class="card m-b-30">
                        <div class="card-body">
                            <table id="datatable-buttons" class="table table-striped table-bordered dt-responsive nowrap" style="border-collapse: collapse; border-spacing: 0; width: 100%; margin-top: 10px; justify-content:center; align-items:center;">
                                @if(session('message-create'))
                                        <div class="alert alert-success" role="alert">
                                            <strong>{{ session('message-create') }}</strong>
                                        </div>
                                    @elseif(session('message-update'))
                                        <div class="alert alert-primary" role="alert">
                                            <strong>{{ session('message-update') }}</strong>
                                        </div>
                                    @elseif(session('message-destroy'))
                                        <div class="alert alert-danger" role="alert">
                                            <strong>{{ session('message-destroy') }}</strong>
                                        </div>
                                    @endif
                                <a class="btn btn-success waves-effect waves-light" data-toggle="modal" data-target="#create" style="float: right; margin-right: 1rem; color:white;">TAMBAH PEGAWAI</a>
                                <thead>
                                    <tr>
                                        <th>NAMA USER</th>
                                        <th>EMAIL</th>
                                        <th>JABATAN</th>
                                        <th>Edit</th>
                                        <th>Hapus</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @forelse ($data as $user)
                                    <tr>
                                        <td>{{ $user->name   }}</td>
                                        <td>{{ $user->email }}</td>
                                        <td>{{ $user->bidang->bidang }}</td>
                        </div>
                        <td>
                            <div class="text-center">
                                <a href="" class="btn btn-primary waves-effect waves-light" data-toggle="modal" data-target="#edit{{ $user->id }}">Edit</a>
                            </div>
                        </td>
                        <td>
                            <div class="text-center">
                                <a href="#" class="btn btn-danger waves-effect waves-light" data-toggle="modal" data-target="#hapus{{ $user->id }}">Hapus</a>
                            </div>
                        </td>
                        </tr>
                        @include('UserSenapelan.editAdmin')
                        @include('UserSenapelan.createAdmin')
                        @include('UserSenapelan.deleteAdmin')
                        @empty
                        <tr>
                            <td colspan="9" class="text-center">
                                <div class="alert alert-danger">Data formulir belum Tersedia.</div>
                            </td>
                        </tr>
                        @endforelse
                    </tbody>
                        </table>
                    </div>
                </div>
            </div> <!-- end col -->
        </div> <!-- end row -->
    </div>
    <!-- container-fluid -->
</div>
<!-- content -->
@include('HeaderFooter.footer')
</div>
<!-- ============================================================== -->
<!-- End Right content here -->
<!-- ============================================================== -->
</div>
<!-- END wrapper -->
<!-- jQuery  -->
<script src="{{ asset('assets/js/jquery.min.js') }}"></script>
<script src="{{ asset('assets/js/bootstrap.bundle.min.js') }}"></script>
<script src="{{ asset('assets/js/metismenu.min.js') }}"></script>
<script src="{{ asset('assets/js/jquery.slimscroll.js') }}"></script>
<script src="{{ asset('assets/js/waves.min.js') }}"></script>

<!-- Required datatable js -->
<script src="{{ asset('plugins/datatables/jquery.dataTables.min.js') }}"></script>
<script src="{{ asset('plugins/datatables/dataTables.bootstrap4.min.js') }}"></script>
<!-- Buttons examples -->
<script src="{{ asset('plugins/datatables/dataTables.buttons.min.js') }}"></script>
<script src="{{ asset('plugins/datatables/buttons.bootstrap4.min.js') }}"></script>
<script src="{{ asset('plugins/datatables/jszip.min.js') }}plugins/datatables/jszip.min.js"></script>
<script src="{{ asset('plugins/datatables/pdfmake.min.js') }}"></script>
<script src="{{ asset('plugins/datatables/vfs_fonts.js') }}"></script>
<script src="{{ asset('plugins/datatables/buttons.html5.min.js') }}"></script>
<script src="{{ asset('plugins/datatables/buttons.print.min.js') }}"></script>
<script src="{{ asset('plugins/datatables/buttons.colVis.min.js') }}"></script>
<!-- Responsive examples -->
<script src="{{ asset('plugins/datatables/dataTables.responsive.min.js') }}"></script>
<script src="{{ asset('plugins/datatables/responsive.bootstrap4.min.js') }}"></script>

<!-- Datatable init js -->
<script src="{{ asset('assets/pages/datatables.init.js') }}"></script>

<!-- App js -->
<script src="{{ asset('assets/js/app.js') }}"></script>

</body>

</html>